### PR TITLE
Added a .gitignore and deleted the pesky .DS_Store file.

### PR DESCRIPTION
**Pull request by needcaffeine**

### CODE REVIEW

**Comment by RichardLitt** [comment]
lgtm. ping @kjw

**Comment by kjw** [comment]
Ah darn OSX users :-).

**Comment by kjw** [comment]
Soz for merge delay on this and the other.

**Comment by needcaffeine** [comment]
It's okay! Thank you for merging in my tiny little commit. Now I'm going to add to my resume that I am a core contributor to the CrossRef API. .............Not really.

**Comment by RichardLitt** [comment]
Cheers.

**Pull request merged**
